# Data exploration

In [1]:
import pandas as pd
import numpy as np

data = {
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry'],
    'Gender':  ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M'],
    'Math':    [85, 62, 90, 45, 78, 55, 92, 38],
    'English': [78, 70, 88, 50, 82, 60, 95, 42],
    'Science': [80, 65, 92, 48, 75, 58, 89, 40],
    'Attend':  [90, 75, 95, 60, 88, 70, 98, 55]
}

df = pd.DataFrame(data)

In [2]:
print(df.shape)
print(df.head(5))
print(df.info())
print(df.describe())

(8, 6)
      Name Gender  Math  English  Science  Attend
0    Alice      F    85       78       80      90
1      Bob      M    62       70       65      75
2  Charlie      M    90       88       92      95
3    David      M    45       50       48      60
4      Eva      F    78       82       75      88
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Gender   8 non-null      object
 2   Math     8 non-null      int64
 3   English  8 non-null      int64
 4   Science  8 non-null      int64
 5   Attend   8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes
None
            Math    English    Science     Attend
count   8.000000   8.000000   8.000000   8.000000
mean   68.125000  70.625000  68.375000  78.875000
std    20.985965  18.661936  18.905309  16.269494
min    38.000000  42.000000  40.000000  55.000000
25%    52.500000  57.500000  55.500000  67.500000
50%    70.000000  74.000000  70.000000  81.500000
75%    86.250000  83.500000  82.250000  91.250000
max    92.000000  95.000000  92.000000  98.000000

In [3]:
df.head()

      Name Gender  Math  English  Science  Attend
0    Alice      F    85       78       80      90
1      Bob      M    62       70       65      75
2  Charlie      M    90       88       92      95
3    David      M    45       50       48      60
4      Eva      F    78       82       75      88

#  Student wise analysis

In [4]:
df

      Name Gender  Math  English  Science  Attend
0    Alice      F    85       78       80      90
1      Bob      M    62       70       65      75
2  Charlie      M    90       88       92      95
3    David      M    45       50       48      60
4      Eva      F    78       82       75      88
5    Frank      M    55       60       58      70
6    Grace      F    92       95       89      98
7    Henry      M    38       42       40      55

In [5]:
df['Total']=df[['Math','English','Science']].sum(axis=1)
df['Average']=df[['Math','English','Science']].mean(axis=1)
df['Grade']=np.where(df['Average']>=80,'A',np.where(df['Average']>=60,'B',np.where(df['Average']>=40,'C','F')))

df[['Name','Total','Average','Grade']]

      Name  Total    Average Grade
0    Alice    243  81.000000     A
1      Bob    197  65.666667     B
2  Charlie    270  90.000000     A
3    David    143  47.666667     C
4      Eva    235  78.333333     B
5    Frank    173  57.666667     C
6    Grace    276  92.000000     A
7    Henry    120  40.000000     C

# Subject wise analysis

In [14]:
df[['Math','English','Science']].mean()
avg=df[['Math','English','Science']].mean()
print(avg.idxmax())
idx=df['Math'].idxmax()
print(df['Name'][idx],df['Math'][idx])
idx=df['English'].idxmax()
print(df['Name'][idx],df['English'][idx])
idx=df['Science'].idxmax()
print(df['Name'][idx],df['Science'][idx])
print((df['Math']>80).sum())
print((df['English']>80).sum())
print((df['Science']>80).sum())

English
Grace 92
Grace 95
Charlie 92
3
3
2

# Gender wise analysis

In [21]:
print(df.groupby('Gender')[['Math','Science','English']].mean())
print(df.groupby('Gender')['Average'].mean().idxmax())
print(df['Gender'].value_counts())

        Math    Science  English
Gender
F       85.0  81.333333     85.0
M       58.0  60.600000     62.0
F
Gender
M    5
F    3
Name: count, dtype: int64

# Attendance analysis

In [22]:
# task 1 — average attendance
print(df['Attend'].mean())

# task 2 — below 75 attendance
print(df[df['Attend'] < 75]['Name'])

# task 3 — correlation between attendance and average
print(df['Attend'].corr(df['Average']))
# close to 1 = strong positive correlation
# close to 0 = no correlation

# task 4 — classify attendance
df['Attend_Status'] = np.where(df['Attend'] >= 90, 'Excellent',
                      np.where(df['Attend'] >= 75, 'Good', 'Poor'))
print(df[['Name', 'Attend', 'Attend_Status']])

78.875
3    David
5    Frank
7    Henry
Name: Name, dtype: object
0.9979054673008121
      Name  Attend Attend_Status
0    Alice      90     Excellent
1      Bob      75          Good
2  Charlie      95     Excellent
3    David      60          Poor
4      Eva      88          Good
5    Frank      70          Poor
6    Grace      98     Excellent
7    Henry      55          Poor

In [7]:
df

      Name Gender  Math  English  Science  Attend  Total    Average Grade
0    Alice      F    85       78       80      90    243  81.000000     A
1      Bob      M    62       70       65      75    197  65.666667     B
2  Charlie      M    90       88       92      95    270  90.000000     A
3    David      M    45       50       48      60    143  47.666667     C
4      Eva      F    78       82       75      88    235  78.333333     B
5    Frank      M    55       60       58      70    173  57.666667     C
6    Grace      F    92       95       89      98    276  92.000000     A
7    Henry      M    38       42       40      55    120  40.000000     C